export const COLORADO_BMX_TRACK_SLUGS = [
  'mile-high-bmx',
  'dacono-bmx',
  'county-line-bmx',
  'twin-silo-bmx',
  'durango-bmx',
  'grand-valley-bmx',
  'eagle-county-bmx',
  'crown-mountain-bmx-park',
  'cortez-bmx',
  'cross-creek-bmx',
  'higher-ground-bmx',
  'longmont-bmx-park',
  'rylans-backyard',
] as const;
